// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmvp9LQPrw9BIOTVKxY7eHXTqJp_2Vog8',
    appId: '1:933227150825:web:e01fb77c24f47d5c6cdf78',
    messagingSenderId: '933227150825',
    projectId: 'ateliers-a60ae',
    authDomain: 'ateliers-a60ae.firebaseapp.com',
    storageBucket: 'ateliers-a60ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjpp9X5DIiVbrqXMGxGoJPI3Ipe0rHLcU',
    appId: '1:933227150825:android:fd03125793eb4e4c6cdf78',
    messagingSenderId: '933227150825',
    projectId: 'ateliers-a60ae',
    storageBucket: 'ateliers-a60ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEYFu5wGXS6ciHqsAFXtZ6JuDFOQ6ivY0',
    appId: '1:933227150825:ios:1766c8d3d9209e656cdf78',
    messagingSenderId: '933227150825',
    projectId: 'ateliers-a60ae',
    storageBucket: 'ateliers-a60ae.appspot.com',
    iosBundleId: 'com.example.appsAteliers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEYFu5wGXS6ciHqsAFXtZ6JuDFOQ6ivY0',
    appId: '1:933227150825:ios:1766c8d3d9209e656cdf78',
    messagingSenderId: '933227150825',
    projectId: 'ateliers-a60ae',
    storageBucket: 'ateliers-a60ae.appspot.com',
    iosBundleId: 'com.example.appsAteliers',
  );
}
